In [1]:
import numpy as np
f= open("E:/R/binary_classification.txt") 

In [2]:
lines = f.readlines()[1:]

In [3]:
print(lines)

['aaa,25,60,5.9,yes\n', 'bbbb,26,67,6.0,no\n', 'cccc,45,78,5.5,yes\n', 'dddd,56,80,5.9,no\n', 'eeee,55,81,6.0,no\n', 'ffffff,56,79,5.11,no\n', 'gggg,55,79,5.4,yes\n', 'iii,56,89,5.9,yes\n', 'hh,49,70,5.6,no\n', 'jjjj,49,75,5.6,yes\n', 'kkkkk,52,80,5.7,yes']


In [4]:
x=[]
y=[]
for line in lines:
    w = line.strip().split(",")
    i = w[1:-1]
    ins = [float(v) for v in i]
    x.append(ins)
    lab = w[-1]
    if lab=="yes":
        y.append(1)
    else:
        y.append(0)
        
    

In [5]:
print(x)

[[25.0, 60.0, 5.9], [26.0, 67.0, 6.0], [45.0, 78.0, 5.5], [56.0, 80.0, 5.9], [55.0, 81.0, 6.0], [56.0, 79.0, 5.11], [55.0, 79.0, 5.4], [56.0, 89.0, 5.9], [49.0, 70.0, 5.6], [49.0, 75.0, 5.6], [52.0, 80.0, 5.7]]


In [6]:
print(y)

[1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1]


## scaling inupt matrix only in classification problem

In [7]:
def sd(x):
    return (((x-x.mean())**2).sum()/(x.size-1))**0.5
def scale(x):
    return (x-x.mean())/sd(x)
def scaleMatrix(x):
    for i in range(x.shape[1]):
        col = x[:,i]
        x[:,i]=scale(col)    
    o = np.ones(x.shape[0])
    return np.c_[o,x]

In [8]:

x = np.array(x)
X =np.array(x)
ins = np.array(x)
X = scaleMatrix(ins)
#print(X)
Y = np.c_[y]
print(Y)


[[1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]


### defining function 

In [9]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def loss(y,ycap):
    return ((y-ycap)**2).mean()

def derivativ(x):
    return x*(1-x)


In [10]:
np.random.seed(101)
W = 2*np.random.random((X.shape[1], Y.shape[1]))
print(W.shape)


(4, 1)


### traning 

In [17]:
ploss=0
flag=0
converg = 0.000009
for i in range(1000):
    ycap = sigmoid(X.dot(W))
    e = Y-ycap
    closs = loss(y,ycap)
    if i%10==0:
        print("current loss",i+1,"itreation",closs)
    diff = abs(ploss-closs)
    if diff<=converg:
        print("training completed after",i+1,"iteration")
        flag=1
        break
    delta =e*derivativ(ycap)
    W+= X.T.dot(delta)
    ploss=closs
if flag==0:
    print("traning not completed increase number of iteration")
    

current loss 1 itreation 0.4011324700769752
current loss 11 itreation 0.4012910622560699
current loss 21 itreation 0.40144703584995084
current loss 31 itreation 0.4016004594461917
current loss 41 itreation 0.4017513991756507
current loss 51 itreation 0.4018999188228075
current loss 61 itreation 0.40204607993018093
current loss 71 itreation 0.4021899418971944
current loss 81 itreation 0.40233156207383014
current loss 91 itreation 0.40247099584939183
current loss 101 itreation 0.4026082967366705
current loss 111 itreation 0.4027435164517902
current loss 121 itreation 0.40287670498998995
current loss 131 itreation 0.4030079106975825
current loss 141 itreation 0.40313718034031304
current loss 151 itreation 0.40326455916832593
current loss 161 itreation 0.4033900909779363
current loss 171 itreation 0.40351381817038795
current loss 181 itreation 0.40363578180776755
current loss 191 itreation 0.4037560216662351
current loss 201 itreation 0.40387457628672213
current loss 211 itreation 0.403991

In [18]:
prob  = sigmoid(X.dot(W))

In [19]:
print(prob)

[[0.99999999]
 [1.        ]
 [0.99999084]
 [0.04426869]
 [0.23041772]
 [0.39156608]
 [0.39649525]
 [0.9967511 ]
 [0.11312405]
 [0.94421093]
 [0.96170723]]


In [20]:
prob[prob<0.5]=0
prob[prob>0.5]=1
print(prob)

[[1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]]


In [21]:
def accuracy(y,ycap):
    c= y==ycap
    return c[c==True].size/y.shape[0]*100

In [22]:
accuracy(Y,prob)

81.81818181818183