In [1]:
f = open("E:/R/winequality-white.txt")

In [2]:
read = f.readline()

In [3]:
lines = f.readlines()


In [4]:
read

'"fixed acidity";"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"\n'

In [5]:
read = read.strip()

In [6]:

read

'"fixed acidity";"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"'

In [7]:
head = read.split(';')

In [8]:
head

['"fixed acidity"',
 '"volatile acidity"',
 '"citric acid"',
 '"residual sugar"',
 '"chlorides"',
 '"free sulfur dioxide"',
 '"total sulfur dioxide"',
 '"density"',
 '"pH"',
 '"sulphates"',
 '"alcohol"',
 '"quality"']

In [9]:
x=[]
y=[]
for line in lines:
    w = line.strip().split(";")
    ins = [float(v) for v in w[0:-1]]
    lab= float(w[-1])
    x.append(ins)
    y.append(lab)

import numpy as np
x = np.array(x)
ones = np.ones(x.shape[0])
X = np.c_[ones,x]
Y = np.c_[y]
np.random.seed(1)
W = 2*np.random.random((X.shape[1],1))-1
#print(W.shape)

def predict(x,w):
    return x.dot(w)

def loss(y,ycap):
    return((y-ycap)**2).mean()

def derivative(x,y,w):
    ycap = predict(x,w)
    return (x.T.dot(y-ycap))/x.shape[0]

ycap1 = predict(X,W)
print('loss:',loss(Y,ycap1))

grad = derivative(X,Y,W)
print(grad)
W+= grad*0.002
ycap2 = predict(X,W)
print('loss:',loss(Y,ycap2))
#scaling
def sd(x):
    return(((x-x.mean())**2).sum()/(x.size-1))**0.5

def scale(x):
    return (x-x.mean())/sd(x)

def scaleMatrix(x):
    for i in range(x.shape[1]):
        cal =x[:,i]
        x[:,i]=scale(cal)
    o = np.ones(x.shape[0])
    return np.c_[o,x]
    

loss: 5301.190220944223
[[6.90201103e+01]
 [4.73613196e+02]
 [1.92310896e+01]
 [2.34154190e+01]
 [5.02726678e+02]
 [3.24685928e+00]
 [2.77636696e+03]
 [1.04492009e+04]
 [6.86470645e+01]
 [2.19978685e+02]
 [3.40809596e+01]
 [7.13137644e+02]]
loss: 10154006.699018393


In [10]:
print(x)
print("_"*30)
print(ins)

[[ 7.    0.27  0.36 ...  3.    0.45  8.8 ]
 [ 6.3   0.3   0.34 ...  3.3   0.49  9.5 ]
 [ 8.1   0.28  0.4  ...  3.26  0.44 10.1 ]
 ...
 [ 6.5   0.24  0.19 ...  2.99  0.46  9.4 ]
 [ 5.5   0.29  0.3  ...  3.34  0.38 12.8 ]
 [ 6.    0.21  0.38 ...  3.26  0.32 11.8 ]]
______________________________
[6.0, 0.21, 0.38, 0.8, 0.02, 22.0, 98.0, 0.98941, 3.26, 0.32, 11.8]


In [11]:

ins = np.array(x)
out = np.array(Y)
X   = scaleMatrix(ins)
YL  = scaleMatrix(out) 
print(x)


[[ 7.    0.27  0.36 ...  3.    0.45  8.8 ]
 [ 6.3   0.3   0.34 ...  3.3   0.49  9.5 ]
 [ 8.1   0.28  0.4  ...  3.26  0.44 10.1 ]
 ...
 [ 6.5   0.24  0.19 ...  2.99  0.46  9.4 ]
 [ 5.5   0.29  0.3  ...  3.34  0.38 12.8 ]
 [ 6.    0.21  0.38 ...  3.26  0.32 11.8 ]]


In [12]:
print(X.shape)


(4898, 12)


In [13]:
print(YL.shape)

(4898, 2)


In [14]:
print(x)

[[ 7.    0.27  0.36 ...  3.    0.45  8.8 ]
 [ 6.3   0.3   0.34 ...  3.3   0.49  9.5 ]
 [ 8.1   0.28  0.4  ...  3.26  0.44 10.1 ]
 ...
 [ 6.5   0.24  0.19 ...  2.99  0.46  9.4 ]
 [ 5.5   0.29  0.3  ...  3.34  0.38 12.8 ]
 [ 6.    0.21  0.38 ...  3.26  0.32 11.8 ]]


In [15]:
print(X)

[[ 1.00000000e+00  1.72079392e-01 -8.17615531e-02 ... -1.24679399e+00
  -3.49148610e-01 -1.39301024e+00]
 [ 1.00000000e+00 -6.57434005e-01  2.15873592e-01 ...  7.39953092e-01
   1.34170957e-03 -8.24191529e-01]
 [ 1.00000000e+00  1.47560044e+00  1.74501618e-02 ...  4.75053481e-01
  -4.36771190e-01 -3.36632638e-01]
 ...
 [ 1.00000000e+00 -4.20430177e-01 -3.79396698e-01 ... -1.31301889e+00
  -2.61526030e-01 -9.05451345e-01]
 [ 1.00000000e+00 -1.60544932e+00  1.16661877e-01 ...  1.00485270e+00
  -9.62506669e-01  1.85738237e+00]
 [ 1.00000000e+00 -1.01293975e+00 -6.77031842e-01 ...  4.75053481e-01
  -1.48824215e+00  1.04478422e+00]]


In [16]:
print(ins)

[[ 1.72079392e-01 -8.17615531e-02  2.13258429e-01 ... -1.24679399e+00
  -3.49148610e-01 -1.39301024e+00]
 [-6.57434005e-01  2.15873592e-01  4.79962210e-02 ...  7.39953092e-01
   1.34170957e-03 -8.24191529e-01]
 [ 1.47560044e+00  1.74501618e-02  5.43782844e-01 ...  4.75053481e-01
  -4.36771190e-01 -3.36632638e-01]
 ...
 [-4.20430177e-01 -3.79396698e-01 -1.19147034e+00 ... -1.31301889e+00
  -2.61526030e-01 -9.05451345e-01]
 [-1.60544932e+00  1.16661877e-01 -2.82528194e-01 ...  1.00485270e+00
  -9.62506669e-01  1.85738237e+00]
 [-1.01293975e+00 -6.77031842e-01  3.78520636e-01 ...  4.75053481e-01
  -1.48824215e+00  1.04478422e+00]]


In [17]:
print(y)

[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 5.0, 5.0, 5.0, 7.0, 5.0, 7.0, 6.0, 8.0, 6.0, 5.0, 8.0, 7.0, 8.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0, 7.0, 6.0, 6.0, 6.0, 6.0, 5.0, 5.0, 5.0, 6.0, 5.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0, 7.0, 4.0, 5.0, 6.0, 5.0, 6.0, 7.0, 7.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 5.0, 6.0, 6.0, 5.0, 7.0, 5.0, 8.0, 5.0, 6.0, 5.0, 5.0, 6.0, 8.0, 5.0, 7.0, 7.0, 5.0, 5.0, 6.0, 6.0, 5.0, 6.0, 5.0, 6.0, 6.0, 6.0, 5.0, 6.0, 6.0, 5.0, 7.0, 7.0, 7.0, 6.0, 6.0, 7.0, 4.0, 6.0, 5.0, 5.0, 5.0, 5.0, 5.0, 6.0, 5.0, 6.0, 6.0, 5.0, 6.0, 5.0, 5.0, 5.0, 5.0, 4.0, 6.0, 6.0, 5.0, 5.0, 5.0, 5.0, 5.0, 6.0, 6.0, 6.0, 5.0, 7.0, 7.0, 6.0, 5.0, 7.0, 5.0, 5.0, 5.0, 5.0, 6.0, 5.0, 7.0, 6.0, 5.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0, 4.0, 7.0, 6.0, 7.0, 6.0, 6.0, 5.0, 6.0, 6.0, 6.0, 7.0, 8.0, 8.0, 7.0, 5.0, 5.0, 6.0, 5.0, 5.0, 6.0, 7.0, 5.0, 5.0, 6.0, 6.0, 4.0, 7.0, 5.0, 6.0, 4.0, 5.0, 4.0, 6.0, 6.0, 5.0, 5.0, 6.0, 5.0, 5.0, 6.0, 5.0, 8.0, 4.0, 6.0, 5.0, 6.0, 5.0, 5.0, 6.0, 5.0, 5.0, 5.0, 5.0,

In [18]:
print(Y)  

[[6.]
 [6.]
 [6.]
 ...
 [6.]
 [7.]
 [6.]]


In [19]:
print(out)

[[0.13785607]
 [0.13785607]
 [0.13785607]
 ...
 [0.13785607]
 [1.26698484]
 [0.13785607]]


In [20]:
print(YL)

[[1.         0.13785607]
 [1.         0.13785607]
 [1.         0.13785607]
 ...
 [1.         0.13785607]
 [1.         1.26698484]
 [1.         0.13785607]]


In [21]:
YL=out

In [22]:
print(YL)

[[0.13785607]
 [0.13785607]
 [0.13785607]
 ...
 [0.13785607]
 [1.26698484]
 [0.13785607]]


In [23]:
def train(x,y,w,alpha,iter,conv=0.000000001):
    ploss=0
    flag=0
    for i in range(iter):
        ycap = predict(x,w)
        closs = loss(y,ycap)
        print(closs)
        if i% 1000==0:
            print("loss at itration",i,"is",closs)
        diff = abs(ploss-closs)
        if diff<=conv:
            print("training completed",i+1,"iteration")
            flag=1
            break
        grad = derivative(x,y,w)
        w+= grad*alpha
        ploss=closs
    if flag==0:
        print("traninig not completed")
    return w
        
    

In [25]:
print(W)

[[-0.02791577]
 [ 1.38787538]
 [-0.96130907]
 [-0.34850402]
 [ 0.29896514]
 [-0.80882909]
 [ 4.92525435]
 [20.58952328]
 [-0.06917092]
 [ 0.51759084]
 [-0.09344905]
 [ 1.79671429]]


In [26]:
theta = np.array(W)
print(theta)
theta = train(X,YL,theta,0.02,1000)
theta = train(X,YL,theta,0.02,8000)


[[-0.02791577]
 [ 1.38787538]
 [-0.96130907]
 [-0.34850402]
 [ 0.29896514]
 [-0.80882909]
 [ 4.92525435]
 [20.58952328]
 [-0.06917092]
 [ 0.51759084]
 [-0.09344905]
 [ 1.79671429]]
544.0435533874762
loss at itration 0 is 544.0435533874762
499.38611986040524
459.47714872306926
423.7594993886061
391.74385265634663
363.0003369470871
337.1511943289998
313.8643569116854
292.84782031194834
273.84471501068606
256.62898877647365
241.00162414740953
226.7873244305839
213.83160996625386
201.9982736585696
191.16715112529215
181.232166378095
172.09961881142135
163.68668153784068
155.92008483701233
148.73496174988685
142.07383570758466
135.88573258617774
130.1254017687455
124.7526327134249
119.73165520472463
115.03061293488965
110.6211013486365
106.47776181093239
102.57792514362593
98.90129844012523
95.42968982325529
92.14676647329541
89.03784183272349
86.08968840162918
83.29037298208573
80.62911161884982
78.09614182446919
75.68260997524516
73.38047202579016
71.1824059187579
69.08173426674392
67.072

In [27]:
def accu(y,ycap,cloesness):
    ds = 100-cloesness
    dist = abs(y-ycap)/abs(y)*100
    pcnt = dist[dist<=ds].size
    n = y.shape[0]
    return pcnt/n*100
 

In [28]:
ycap = predict(X,theta)
print(ycap)

[[-0.35563662]
 [-0.74541581]
 [-0.12722857]
 ...
 [-0.60439616]
 [ 0.78305894]
 [ 0.52972597]]


In [29]:
yc  = ycap*sd(Y)+Y.mean()

In [30]:
print(yc)

[[5.56294384]
 [5.21774036]
 [5.76523082]
 ...
 [5.34263279]
 [6.57141655]
 [6.3470551 ]]


In [ ]:
accu(Y,yc,90)

In [ ]:
# Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
    


In [ ]:
dataset_minmax(X)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("E:/R/winequality-white.csv",sep=';')
df.head()

In [ ]:
import seaborn as sns

In [ ]:
x =df.iloc[:,:-1]
y = df['quality']

In [ ]:
from sklearn.model_selection import train_test_splitplit

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train,y_train)

In [ ]:
model.intercept_

In [ ]:
model.coef_

In [ ]:
predict = model.predict(x_test)
predict

In [ ]:
residual  = (predict-y_test)**2
residual

In [ ]:
model.score(x_test,y_test)

In [ ]:
model.score(x_train,y_train)

In [ ]:
predicate_train = model.predict(x_train)

In [ ]:
error = (predicate_train-y_train)**2
error

In [ ]:
error.max() #train

In [ ]:
residual.max() #test