In [1]:
import numpy as np
f= open("E:/R/multinomila_patients_3label.txt")

In [2]:
lines = f.readlines()[1:]

In [3]:
print(lines)

['aa,20,25,5.2,low\n', 'bb,22,56,6.1,high\n', 'cc,24,45,6.0,moderat\n', 'dd,25,35,4.7,low\n', 'ee,23,45,3.5,low\n', 'ff,22,55,6.0,high\n', 'gg,34,74,5.5,high\n', 'hh,43,80,5.9,moderat\n', 'ii,72,43,6.3,moderat\n', 'jj,43,54,6.6,high\n', 'kk,74,55,5.5,low\n', 'll,76,54,4.5,low']


In [4]:
x=[]
label=[]
for line in lines:
    w = line.strip().lower().split(",")
    ins = [float(v) for v in w[1:-1]]
    x.append(ins)
    lab = w[-1]
    label.append(lab)

In [5]:
print(lab)

low


In [6]:
print(label)

['low', 'high', 'moderat', 'low', 'low', 'high', 'high', 'moderat', 'moderat', 'high', 'low', 'low']


In [7]:
print(np.c_[x])

[[20.  25.   5.2]
 [22.  56.   6.1]
 [24.  45.   6. ]
 [25.  35.   4.7]
 [23.  45.   3.5]
 [22.  55.   6. ]
 [34.  74.   5.5]
 [43.  80.   5.9]
 [72.  43.   6.3]
 [43.  54.   6.6]
 [74.  55.   5.5]
 [76.  54.   4.5]]


In [8]:
print(label)

['low', 'high', 'moderat', 'low', 'low', 'high', 'high', 'moderat', 'moderat', 'high', 'low', 'low']


In [9]:
print(label)

['low', 'high', 'moderat', 'low', 'low', 'high', 'high', 'moderat', 'moderat', 'high', 'low', 'low']


### assigning uniqe numerical label for string label

In [10]:
d ={label:i for i,label in enumerate(list(set(label)))}

In [11]:
print(d)

{'low': 0, 'moderat': 1, 'high': 2}


### convert all string label into numeric label


In [12]:
y = [d[l] for l in label]                

In [13]:
print(y)

[0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 0]


### transform numeric label to into binarray array 

In [14]:
b=[]
for i in y:
    barr = np.zeros(len(set(y)))
    barr[i]=1
    b.append(barr)

### jhfg

# dfdg

In [15]:
print(b)

[array([1., 0., 0.]), array([0., 0., 1.]), array([0., 1., 0.]), array([1., 0., 0.]), array([1., 0., 0.]), array([0., 0., 1.]), array([0., 0., 1.]), array([0., 1., 0.]), array([0., 1., 0.]), array([0., 0., 1.]), array([1., 0., 0.]), array([1., 0., 0.])]


In [35]:
import numpy as np
X = np.c_[b]
print(X)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [17]:
print(y)

[0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 0]


In [18]:
Y= np.array(b) 

In [19]:
print(Y)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [20]:
Y = np.c_[Y]
print(Y)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [21]:
def sd(x):
    num=((x-x.mean())**2).sum()
    den = x.size-1
    return (num/den)**0.5


def scale(x):
    return (x-x.mean())/sd(x)


def scaleMatrix(x):
    
    for col in range(x.shape[1]):
        x[:,col]= scale(x[:,col])
    ones = np.ones(x.shape[0])
    return np.c_[ones,x]

In [22]:
x = np.array(x)

In [23]:
print(x)


[[20.  25.   5.2]
 [22.  56.   6.1]
 [24.  45.   6. ]
 [25.  35.   4.7]
 [23.  45.   3.5]
 [22.  55.   6. ]
 [34.  74.   5.5]
 [43.  80.   5.9]
 [72.  43.   6.3]
 [43.  54.   6.6]
 [74.  55.   5.5]
 [76.  54.   4.5]]


In [24]:
print(x.shape)

(12, 3)


In [25]:
X = scaleMatrix(x)

In [26]:
print(X)

[[ 1.         -0.89951806 -1.77218042 -0.32050069]
 [ 1.         -0.80881036  0.28156138  0.69756033]
 [ 1.         -0.71810266 -0.44718571  0.58444244]
 [ 1.         -0.6727488  -1.10968307 -0.88609015]
 [ 1.         -0.76345651 -0.44718571 -2.24350484]
 [ 1.         -0.80881036  0.21531164  0.58444244]
 [ 1.         -0.26456414  1.47405661  0.01885298]
 [ 1.          0.14362053  1.87155502  0.47132455]
 [ 1.          1.45888224 -0.57968518  0.92379611]
 [ 1.          0.14362053  0.1490619   1.26314978]
 [ 1.          1.54958994  0.21531164  0.01885298]
 [ 1.          1.64029765  0.1490619  -1.11232593]]


In [27]:
print(Y)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [28]:
def prediction(x):
    return 1/(1+np.exp(-x))
def losss(y,ycap):
    return (y*np.log(ycap)).sum()*-1
def loss(y,ycap):
    return ((y-ycap)**2).mean()
def derivative(x):
    return x*(1-x)



In [29]:
np.random.seed(101)
W = 2*np.random.random((X.shape[1],Y.shape[1]))-1
print(W)

[[ 0.03279726  0.14133517 -0.94305155]
 [-0.65695669  0.37055396  0.66779373]
 [-0.38606756  0.78722616  0.44308772]
 [-0.62012209  0.10845518 -0.29573609]]


In [30]:
ploss=0
flag=0
cov =1e-9
for i in range(100000):
    ycap = prediction(X.dot(W))
    e = Y-ycap
    closs = loss(Y,ycap)
    if i%10==0:
        print("current loss at", i+1,"iteration", closs)
    if abs(ploss-closs)<=cov:
        print("Traning is compelet after",i+1,"itration")
        flag=1
        break
    delta = e*derivative(ycap)
    W+= X.T.dot(delta)
    ploss=closs
if flag==0:
    print("traning is not completed")

current loss at 1 iteration 0.249441503801451
current loss at 11 iteration 0.09355007049573877
current loss at 21 iteration 0.08889631552491113
current loss at 31 iteration 0.08685497001497629
current loss at 41 iteration 0.08569155699430445
current loss at 51 iteration 0.08493561320311611
current loss at 61 iteration 0.08440236290101737
current loss at 71 iteration 0.08400388834377
current loss at 81 iteration 0.08369278225607733
current loss at 91 iteration 0.08344101519319586
current loss at 101 iteration 0.08323071260457399
current loss at 111 iteration 0.08304963786759251
current loss at 121 iteration 0.08288874418584918
current loss at 131 iteration 0.08274069896128519
current loss at 141 iteration 0.0825988773290763
current loss at 151 iteration 0.08245658528618746
current loss at 161 iteration 0.08230642916651972
current loss at 171 iteration 0.08213989606908227
current loss at 181 iteration 0.08194738283834822
current loss at 191 iteration 0.08171903788891012
current loss at 2

### accuracy testing

In [31]:
probs = prediction(X.dot(W))

In [32]:
print(probs)

[[9.97691318e-01 3.61755011e-41 1.00357994e-02]
 [1.00939977e-06 7.41636224e-16 8.55468975e-01]
 [6.08721571e-05 3.70832236e-21 4.90637806e-01]
 [9.99997388e-01 1.46887635e-40 2.34808055e-03]
 [1.00000000e+00 4.96221481e-51 1.05775274e-04]
 [5.90865042e-06 1.75064761e-17 7.86053322e-01]
 [3.15193781e-03 5.17771712e-10 4.63398299e-01]
 [9.28038231e-06 9.82728309e-01 6.80192269e-01]
 [4.85436109e-03 9.75720174e-01 3.52080340e-03]
 [2.62306734e-08 2.20435258e-02 6.38576751e-01]
 [9.94707623e-01 2.24238454e-02 5.02205027e-04]
 [1.00000000e+00 8.56434275e-14 8.50655088e-06]]


### transform probabilites into binary array

In [33]:
probs[probs>0.5]=1
probs[probs<0.5]=0
print(probs)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


### convert binary array into numerical label

In [36]:
Yc = [int(np.where(arr==1)[0]) for arr in probs] 

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
print(Yc)

In [ ]:
btn = np.where(probs==1)[1]

In [ ]:
print(btn)

In [ ]:
print(np.c_[Y,Yc])

In [ ]:
def accuracy(y,ycap):
    c= y==ycap
    return c[c==True].size/y.shape[0]*100

In [ ]:
y = np.array(y)

In [ ]:
accuracy(y,Yc)