In [2]:
import numpy as np
f = open("E:/R/multinomila_patients_3label.txt")

In [3]:
h =f.readline()


In [4]:
lines= f.readlines()

In [5]:
x=[]
label=[]
for line in lines:
    w = line.strip().split(",")
    ins = w[1:-1]
    inputs= [float(v) for v in ins]
    x.append(inputs)
    label.append(w[-1])
    


In [6]:
print(x)

[[20.0, 25.0, 5.2], [22.0, 56.0, 6.1], [24.0, 45.0, 6.0], [25.0, 35.0, 4.7], [23.0, 45.0, 3.5], [22.0, 55.0, 6.0], [34.0, 74.0, 5.5], [43.0, 80.0, 5.9], [72.0, 43.0, 6.3], [43.0, 54.0, 6.6], [74.0, 55.0, 5.5], [76.0, 54.0, 4.5]]


In [7]:
print(label)

['low', 'high', 'moderat', 'low', 'low', 'high', 'high', 'moderat', 'moderat', 'high', 'low', 'low']


In [8]:
def sd(x):
    return (((x-x.mean())**2).sum()/(x.size-1))**0.5

def scale(x): 
    return (x-x.mean())/sd(x)

def scaleMAtrix(x):
    for i in range(x.shape[1]):
        cal = x[:,i]
        x[:,i]=scale(cal)
    o = np.ones(x.shape[0])
    return np.c_[o,x]

In [9]:
x= np.array(x)


In [10]:
print(x)

[[20.  25.   5.2]
 [22.  56.   6.1]
 [24.  45.   6. ]
 [25.  35.   4.7]
 [23.  45.   3.5]
 [22.  55.   6. ]
 [34.  74.   5.5]
 [43.  80.   5.9]
 [72.  43.   6.3]
 [43.  54.   6.6]
 [74.  55.   5.5]
 [76.  54.   4.5]]


In [11]:
X = scaleMAtrix(x)

In [12]:
print(X)

[[ 1.         -0.89951806 -1.77218042 -0.32050069]
 [ 1.         -0.80881036  0.28156138  0.69756033]
 [ 1.         -0.71810266 -0.44718571  0.58444244]
 [ 1.         -0.6727488  -1.10968307 -0.88609015]
 [ 1.         -0.76345651 -0.44718571 -2.24350484]
 [ 1.         -0.80881036  0.21531164  0.58444244]
 [ 1.         -0.26456414  1.47405661  0.01885298]
 [ 1.          0.14362053  1.87155502  0.47132455]
 [ 1.          1.45888224 -0.57968518  0.92379611]
 [ 1.          0.14362053  0.1490619   1.26314978]
 [ 1.          1.54958994  0.21531164  0.01885298]
 [ 1.          1.64029765  0.1490619  -1.11232593]]


In [13]:
d = {w:i for i,w in enumerate(list(set(label)))}

In [14]:
print(d)


{'low': 0, 'moderat': 1, 'high': 2}


In [15]:
#transfor all label into numeric label
num = [d[l] for l in label]

In [16]:
num

[0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 0]

In [17]:
#transform numeric label into binaray array
b=[]
for i in num:
    barr = np.zeros(len(set(num)))
    barr[i]=1
    b.append(barr)
    

In [18]:
#label matrix with binarry array
Y = np.array(b)

Y = np.c_[Y]
print(Y)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [19]:
def Sigmoid(x):
    return 1/(1+np.exp(-x))
def pred(x,w):
    r = x
    for i in w:
        r=  Sigmoid(x.dot(i))
    return r
def derivativ(x):
    return x*(1-x)
def losss(y,ycap):
    return (y*np.log(ycap)).sum()*-1
def loss(y,ycap):
    return ((y-ycap)**2).mean()

    


print(label)
print(num)
print(Y)

['low', 'high', 'moderat', 'low', 'low', 'high', 'high', 'moderat', 'moderat', 'high', 'low', 'low']
[0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 0]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [20]:
#intiate random weight
np.random.seed(101)
r1 = X.shape[1]

In [21]:
h1 = int(r1*1.5)
h2 = int(h1*1.5)
h3 = h1
op = Y.shape[1]

In [24]:
W1 = 5*np.random.random((r1,h1))-1
W2 = 2*np.random.random((h1,h2))-1
W3 = 2*np.random.random((h2,h3))-1
W4 = 2*np.random.random((h3,op))-1
print(W1)
print(W2.shape)
print(W3.shape)
print(W4.shape)
np.random.random()

[[ 0.23089606  2.90222053 -0.77245169  3.42520594  0.3821061   1.90462201]
 [ 3.55331131  3.96295523 -0.6888798   3.64240719  1.58580303  3.72691043]
 [ 1.73465542  0.32080815  2.2360674   1.31492698  2.15503576  1.5561815 ]
 [ 0.11190443  2.67247694  2.99830683  3.38310829  0.51311901  2.04635833]]
(6, 9)
(9, 6)
(6, 3)


0.6933472351522674

In [23]:
#Train
ploss=0
flag=0
conv = 1e-9
for i in range(1000000):
    l1 = Sigmoid(X.dot(W1))
    l2 = Sigmoid(l1.dot(W2))
    l3 = Sigmoid(l2.dot(W3))
    l4 = Sigmoid(l3.dot(W4))
   
    closs = loss(Y,l4)
    if i%1000==0:
        print("current loss",closs)
    if abs(ploss-closs)<=conv:
        print("tranining complete")
        flag = 1
        break
        
    e4 = Y-l4
    d4 = e4*derivativ(l4)
    e3 = d4.dot(W4.T)
    d3 = e3*derivativ(l3)
    e2 = d3.dot(W3.T)
    d2 = e2*derivativ(l2)
    e1 = d2.dot(W2.T)
    d1 = e1*derivativ(l1)
    
    W1+= X.T.dot(d1)
    W2+= l1.T.dot(d2)
    W3+= l2.T.dot(d3)
    W4+= l3.T.dot(d4)
    
    ploss= closs
if flag ==0:
    print("Traninig not completed")
    
    
    

current loss 0.2630824986566051
current loss 9.350020594298724e-05
current loss 4.187528539183296e-05
current loss 2.6671114279451837e-05
current loss 1.9460123878715032e-05
current loss 1.526910610705567e-05
current loss 1.253665666226776e-05
current loss 1.0617735910270686e-05
current loss 9.198030500995447e-06
tranining complete


In [23]:
def pred(x,w):
    r=x
    for i in w:
        r=Sigmoid(r.dot(i))
    return r   

In [24]:
yc=pred(X,[W1,W2,W3,W4])

In [25]:
print(yc)

[[9.96956657e-01 4.28405006e-05 3.41913543e-03]
 [5.50716162e-05 9.97542049e-01 3.07690167e-03]
 [4.76831075e-03 4.71312828e-03 9.92009577e-01]
 [9.97025336e-01 4.24407501e-05 3.34730058e-03]
 [9.97232375e-01 4.00633677e-05 3.17482097e-03]
 [5.75054164e-05 9.97184027e-01 3.40390826e-03]
 [6.31360086e-05 9.95547582e-01 5.14127476e-03]
 [2.19268587e-03 4.49584718e-03 9.95584255e-01]
 [4.18545018e-03 1.47955384e-03 9.96478757e-01]
 [6.03835260e-05 9.96727288e-01 3.76573856e-03]
 [9.96495799e-01 2.74991082e-05 3.93194156e-03]
 [9.97483210e-01 2.67498115e-05 2.62062991e-03]]


In [26]:
yc[yc>0.5]=1
yc[yc<0.5]=0
print(yc)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [27]:
Yc = [int(np.where(arr==1)[0]) for arr in yc] 

In [28]:
print(Yc)

[0, 1, 2, 0, 0, 1, 1, 2, 2, 1, 0, 0]


In [29]:
def accuracy(y,ycap):
    c= y==ycap
    return c[c==True].size/y.shape[0]*100

In [30]:
accuracy(np.array(num),Yc)

100.0

In [39]:
sample = np.random.rand(3, 5)
print(sample)

[[0.59942834 0.45799236 0.15443743 0.34367565 0.50098003]
 [0.56740736 0.03516661 0.65712057 0.29727266 0.59561068]
 [0.60781036 0.47712018 0.66348023 0.59364482 0.82750544]]


In [40]:
sample1 = np.random.random_sample((3, 5))
print(sample)

[[0.59942834 0.45799236 0.15443743 0.34367565 0.50098003]
 [0.56740736 0.03516661 0.65712057 0.29727266 0.59561068]
 [0.60781036 0.47712018 0.66348023 0.59364482 0.82750544]]


In [66]:
sample3= np.random.random((3,5))
print(sample3)

[[0.68913435 0.4902087  0.14215381 0.53385991 0.05080687]
 [0.89271852 0.74791018 0.02457922 0.284852   0.42510608]
 [0.97544924 0.02247369 0.26014278 0.39412181 0.81974193]]


In [74]:
b = 2*np.random.random((3,5))-1
print(b)

[[-0.4332064   0.99244901  0.97634475 -0.01478116 -0.10002779]
 [ 0.86133848  0.77697675  0.99197349  0.8852085  -0.52800261]
 [ 0.73752381 -0.88648467  0.27550391  0.87658084  0.87331374]]


In [78]:
a = np.array((2,4))

In [80]:
aa = 2*a-1
print(aa)

[3 7]
