In [1]:
import numpy as np

In [14]:
age = np.array([40,22,33,45,51,64])
wgt = np.array([22,44,62,81,100,62])
hgt = np.array([4.1,5.2,4.3,7.4,5.5,6.6])


In [15]:
o= np.ones(len(age))

In [16]:
print(o)

[1. 1. 1. 1. 1. 1.]


In [71]:
def poly(x,d):
    M=[]
    for c in range(x.shape[1]):
        col = x[:,c]
        for i in range(d):
            M.append(col**(i+1))
    o = np.ones(x.shape[0])
    M= np.array(M).T
    return np.c_[o,M]



In [76]:
X = np.c_[age,wgt,hgt]
print(X)

[[ 40.   22.    4.1]
 [ 22.   44.    5.2]
 [ 33.   62.    4.3]
 [ 45.   81.    7.4]
 [ 51.  100.    5.5]
 [ 64.   62.    6.6]]


In [73]:

L = poly(X,1)

0
[40. 22. 33. 45. 51. 64.]
1
[ 22.  44.  62.  81. 100.  62.]
2
[4.1 5.2 4.3 7.4 5.5 6.6]
[[ 40.   22.    4.1]
 [ 22.   44.    5.2]
 [ 33.   62.    4.3]
 [ 45.   81.    7.4]
 [ 51.  100.    5.5]
 [ 64.   62.    6.6]]


In [64]:
print(L)

[[  1.   40.   22.    4.1]
 [  1.   22.   44.    5.2]
 [  1.   33.   62.    4.3]
 [  1.   45.   81.    7.4]
 [  1.   51.  100.    5.5]
 [  1.   64.   62.    6.6]]


In [ ]:
Q = poly(X,2)

In [ ]:
print(Q)